# Utiliser une image Node.js pour le développement
FROM node:18

# Définir le répertoire de travail
WORKDIR /app

# Copier uniquement les fichiers nécessaires pour installer les dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le projet dans le conteneur
COPY . .

# Exposer le port utilisé par Vite
EXPOSE 80

# Commande pour démarrer le serveur de développement
CMD ["npm", "run", "dev", "--", "--host"]


# # Utiliser une image Deno officielle
# FROM denoland/deno:1.33.4

# # Définir le répertoire de travail
# WORKDIR /app

# # Copier les fichiers nécessaires dans le conteneur
# COPY . .

# # Exposer le port utilisé par Deno
# EXPOSE 5173

# # Définir les permissions nécessaires pour Deno
# # --allow-net : Permet les connexions réseau
# # --allow-read : Permet la lecture des fichiers locaux
# CMD ["run", "--allow-net", "--allow-read", "--watch", "src/main.ts"]

